Listen 8081

# 通常サイト: http://localhost:8080/
<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /var/www/html/app/webroot

    <Directory /var/www/html/app/webroot>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/main_error.log
    CustomLog ${APACHE_LOG_DIR}/main_access.log combined
</VirtualHost>

# 管理画面: http://localhost:8081/
<VirtualHost *:8081>
    ServerName localhost
    DocumentRoot /var/www/html/kanri/app/webroot

    <Directory /var/www/html/kanri/app/webroot>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/kanri_error.log
    CustomLog ${APACHE_LOG_DIR}/kanri_access.log combined
</VirtualHost>
